# Generated by Django 3.0.3 on 2020-09-20 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('characters', models.TextField()),
                ('tags', models.CharField(max_length=20)),
                ('IMDb_rating', models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='3', max_length=1)),
                ('ticket_price', models.CharField(max_length=4)),
                ('poster', models.ImageField(upload_to='images')),
                ('duration', models.CharField(max_length=20)),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Theatre')),
            ],
        ),
    ]
