# Generated by Django 3.0.3 on 2020-09-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200920_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tier', models.CharField(choices=[('1', 'Silver'), ('2', 'Gold'), ('3', 'Platinum')], default='2', max_length=1)),
                ('persons', models.CharField(max_length=20)),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movies')),
            ],
        ),
    ]
