# Generated by Django 3.0.3 on 2020-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Tier',
            field=models.CharField(choices=[('1', 'Silver'), ('2', 'Gold'), ('3', 'Platinum')], default='2', max_length=1),
        ),
        migrations.AddField(
            model_name='movies',
            name='persons',
            field=models.IntegerField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='movies',
            name='ticket_price',
            field=models.IntegerField(max_length=4),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
