# Generated by Django 3.0.3 on 2020-09-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200921_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tier', models.CharField(choices=[('1', 'Silver'), ('2', 'Gold'), ('3', 'Platinum')], default='2', max_length=1)),
                ('persons', models.IntegerField(default=1, max_length=20)),
            ],
        ),
    ]
